Repository MicrosoftDocs/azure-docs.ru-ru, pull requests merged in 2019-05, with the labels that each got.

#212 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#213 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#214 Fix mistranslation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, In Progress

#215 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, In Progress

#221 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#220 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, In Progress

#217 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#218 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#219 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted, In Progress

#222 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: In Progress

#223 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: In Progress

#224 Fix mistranslation
  articles/data-factory/connector-azure-database-for-mysql.md
Labels: In Progress

#216 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#225 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#226 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#227 Fix mistranslation
  articles/data-factory/connector-concur.md
Labels: Accepted, In Progress

#228 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#229 Fix mistranslation
  articles/data-factory/connector-dynamics-ax.md
Labels: Accepted, In Progress

#231 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#230 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, In Progress

#232 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#233 Fix mistranslation
  articles/data-factory/connector-google-adwords.md
Labels: Accepted, In Progress

#234 Fix mistranslation
  articles/data-factory/connector-google-bigquery.md
Labels: Accepted, In Progress

#236 Fix mistranslation
  articles/data-factory/connector-hbase.md
Labels: Accepted, In Progress

#237 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted, In Progress

#239 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#238 Fix mistranslation
  articles/data-factory/connector-hive.md
Labels: Accepted, In Progress

#240 Fix mistranslation
  articles/data-factory/connector-impala.md
Labels: Accepted, In Progress

#241 Fix mistranslation
  articles/data-factory/connector-jira.md
Labels: Accepted, In Progress

#244 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#242 Fix mistranslation
  articles/data-factory/connector-magento.md
Labels: Accepted, In Progress

#245 Fix mistranslation
  articles/data-factory/connector-mongodb.md
Labels: Accepted, In Progress

#246 Fix mistranslation
  articles/data-factory/connector-mysql.md
Labels: Accepted, In Progress

#247 Fix mistranslation
  articles/data-factory/connector-netezza.md
Labels: Accepted, In Progress

#248 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted, In Progress

#249 Fix mistranslation
  articles/data-factory/connector-odbc.md
Labels: Accepted, In Progress

#250 Fix mistranslation
  articles/data-factory/connector-oracle-eloqua.md
Labels: Accepted, In Progress

#251 Fix mistranslation
  articles/data-factory/connector-oracle-service-cloud.md
Labels: Accepted, In Progress

#252 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#253 Fix mistranslation
  articles/data-factory/connector-paypal.md
Labels: Accepted, In Progress

#255 Fix mistranslation
  articles/data-factory/connector-presto.md
Labels: Accepted, In Progress

#254 Fix mistranslation
  articles/data-factory/connector-phoenix.md
Labels: Accepted, In Progress

#256 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#257 Fix mistranslation
  articles/data-factory/connector-salesforce-marketing-cloud.md
Labels: Accepted, In Progress

#258 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#259 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#260 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#261 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted, In Progress

#264 Fix mistranslation
  articles/data-factory/connector-servicenow.md
Labels: Accepted, In Progress

#262 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#263 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#265 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#266 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress

#267 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress

#268 Fix mistranslation
  articles/data-factory/connector-square.md
Labels: Accepted, In Progress

#272 Fix mistranslation
  articles/data-factory/connector-zoho.md
Labels: Accepted, Linguistic Suggestion

#270 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#273 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#271 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, Linguistic Suggestion

#274 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#276 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#275 Fix mistranslation
  articles/data-factory/how-to-create-tumbling-window-trigger.md
Labels: Accepted, Linguistic Suggestion

#277 Fix mistranslation
  articles/data-factory/store-credentials-in-key-vault.md
Labels: Accepted, Linguistic Suggestion

#278 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-documentdb-connector.md
Labels: Accepted, Linguistic Suggestion

#280 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted, Linguistic Suggestion

#279 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: Accepted, Linguistic Suggestion

#281 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#282 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#283 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
Labels: Accepted, In Progress

#285 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#286 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#284 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#288 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#289 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#287 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#290 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#291 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#292 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#294 Fix mistranslation
  articles/data-factory/v1/data-factory-odata-connector.md
Labels: Accepted, Linguistic Suggestion

#293 Fix mistranslation
  articles/data-factory/v1/data-factory-map-reduce.md
Labels: Accepted, Linguistic Suggestion

#296 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#297 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, In Progress

#298 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
